name: "卵石和贝壳"
description: "在海边玩耍的男孩"

exclude: [README.md, Makefile]

url: https://xienotes.github.io
baseurl: ""

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
  math_engine: mathjax
  parse_block_html: true

plugins:
  - jekyll-paginate
paginate: 20
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

#sass:
#    style: :compressed
#    sass_dir: assets/css/