name: "海边捡点贝壳"
description: "个人笔记"

exclude: [README.md, Makefile]

url: https://xienotes.github.io
baseurl: ""

permalink: /:year/:month/:day/:title.html

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
  math_engine: mathjax
  parse_block_html: true

plugins:
  - jekyll-paginate
paginate: 20
paginate_path: /page-:num

front_page_post: 10


#disqus-id: your-disqus-id

source: .
destination: ./_site

#sass:
#    style: :compressed
#    sass_dir: assets/css/

excerpt_separator: <!--more-->