name: "海边捡点贝壳"
description: "个人笔记"
author: xieyn
keywords: [岩土, Mathematica]

exclude: [README.md, Makefile, vendor]

url: https://xienotes.net
baseurl: ""

permalink: /:year/:month/:day/:title.html

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
  math_engine: mathjax
  parse_block_html: true

front_page_post: 10

source: .
destination: ./_site

#sass:
#    style: :compressed
#    sass_dir: assets/css/

excerpt_separator: <!--more-->

# header navigation
navigation:
  - name: 主页
    url: /
  - name: 归档
    url: /archive.html
  - name: 分类
    url: /categories.html
  - name: 标签
    url: /tags.html
  - name: 收藏
    url: /collections.html
  - name: 搜索
    url: /search.html

# table of contents set up
toc_max: 3

# config for Algolia search
algolia:
   application_id: "IVH7JFNAZ7"
   index_name: "xienotes"
   search_only_api_key: "c9518e033e1e16df88a55d9df7824da7"
   extensions_to_index: 
      - html
      - md
   nodes_to_index: 'p,blockquote,li,code'
   files_to_exclude: [index.html, archive.html, tags.html, categories.html, search.html]

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff",".gif"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################   