name: "海边捡点贝壳"
description: "个人笔记"
author: xieyn
keywords: [岩土, Mathematica]

exclude: [README.md, Makefile]

url: https://xienotes.net
baseurl: ""

permalink: /:year/:month/:day/:title.html

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
  math_engine: mathjax
  parse_block_html: true

front_page_post: 10

source: .
destination: ./_site

#sass:
#    style: :compressed
#    sass_dir: assets/css/

excerpt_separator: <!--more-->

# header navigation
navigation:
  - name: 主页
    url: /
  - name: 归档
    url: /archive.html
  - name: 分类
    url: /categories.html
  - name: 标签
    url: /tags.html
  - name: 收藏
    url: /collections.html
  - name: 搜索
    url: /search.html

# table of contents set up
toc_max: 3